theme: jekyll-theme-minimal
title: <div align="center">BICMEE 2020</div>
description: <div align="center">2020 Workshop on <strong>Bio-Inspired Computing for Miniaturization and Energy Efficiency</strong><br><img src="asu_logo.png"><br><img src="darpa_logo.jpg"></div>
logo: locust_brain.png

github:
  is_project_page: false
