theme: jekyll-theme-slate
title: 2019 Workshop on Insect-Inspired Models for Social Behavior (WIIMSB 2019)
description: ASU-hosted meeting among DARPA SBIR performers and potential collaborators to discuss insect-inspired models of multi-agent system behavior.
