theme: jekyll-theme-minimal
title: BICMEE 2020
description: 2020 Workshop on <strong>Bio-Inspired Computing for Miniaturization and Energy Efficiency</strong><br><br><img src="asu_fse_logo.png"><br><img src="darpa_log.png">
logo: locust_brain.png

github:
  is_project_page: false
